version: '3'

services:
  app:
    env_file:
      - ./docker-compose-vars.env
#    image:
#      quay.io/rywillia/task-manager:latest
    build:
      context: .
      args:
        - APP_PORT=${APP_PORT}
    restart: always
    ports:
      - "${APP_PORT}:${APP_PORT}"
    depends_on:
      - db
  db:
    image:
      quay.io/sclorg/postgresql-15-c9s:latest
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - ./docker-compose-vars.env
